/**
 * Kuratierte Icon-Auswahl für den Vocal-Tag Icon-Picker.
 *
 * Jede Bibliothek enthält eine handverlesene Auswahl an Icons,
 * die für Gesangstechnik-Tags relevant sind (Musik, Stimme, Emotion, etc.).
 */

export interface IconChoice {
  icon: string;
  label: string;
}

export interface IconLibrary {
  id: string;
  name: string;
  prefix: string;
  icons: IconChoice[];
}

export const ICON_LIBRARIES: IconLibrary[] = [
  {
    id: "lucide",
    name: "Lucide",
    prefix: "lucide",
    icons: [
      { icon: "lucide:mic", label: "Microphone" },
      { icon: "lucide:mic-vocal", label: "Vocal" },
      { icon: "lucide:music", label: "Music" },
      { icon: "lucide:music-2", label: "Music 2" },
      { icon: "lucide:music-3", label: "Music 3" },
      { icon: "lucide:music-4", label: "Music 4" },
      { icon: "lucide:guitar", label: "Guitar" },
      { icon: "lucide:drum", label: "Drum" },
      { icon: "lucide:piano", label: "Piano" },
      { icon: "lucide:headphones", label: "Headphones" },
      { icon: "lucide:volume-2", label: "Volume High" },
      { icon: "lucide:volume-1", label: "Volume Low" },
      { icon: "lucide:volume-x", label: "Mute" },
      { icon: "lucide:audio-waveform", label: "Waveform" },
      { icon: "lucide:audio-lines", label: "Audio Lines" },
      { icon: "lucide:bell", label: "Bell" },
      { icon: "lucide:zap", label: "Bolt" },
      { icon: "lucide:flame", label: "Fire" },
      { icon: "lucide:heart", label: "Heart" },
      { icon: "lucide:star", label: "Star" },
      { icon: "lucide:sun", label: "Sun" },
      { icon: "lucide:moon", label: "Moon" },
      { icon: "lucide:cloud", label: "Cloud" },
      { icon: "lucide:wind", label: "Wind" },
      { icon: "lucide:droplets", label: "Water" },
      { icon: "lucide:snowflake", label: "Snowflake" },
      { icon: "lucide:feather", label: "Feather" },
      { icon: "lucide:hand", label: "Hand" },
      { icon: "lucide:smile", label: "Smile" },
      { icon: "lucide:frown", label: "Sad" },
      { icon: "lucide:circle-alert", label: "Exclamation" },
      { icon: "lucide:triangle-alert", label: "Warning" },
      { icon: "lucide:info", label: "Info" },
      { icon: "lucide:arrow-up", label: "Arrow Up" },
      { icon: "lucide:arrow-down", label: "Arrow Down" },
      { icon: "lucide:arrow-up-down", label: "Arrows Up Down" },
      { icon: "lucide:rotate-cw", label: "Rotate" },
      { icon: "lucide:repeat", label: "Repeat" },
      { icon: "lucide:pause", label: "Pause" },
      { icon: "lucide:play", label: "Play" },
      { icon: "lucide:square", label: "Stop" },
      { icon: "lucide:fast-forward", label: "Forward" },
      { icon: "lucide:rewind", label: "Backward" },
      { icon: "lucide:message-circle", label: "Comment" },
      { icon: "lucide:quote", label: "Quote" },
      { icon: "lucide:sparkles", label: "Magic" },
      { icon: "lucide:signal", label: "Signal" },
      { icon: "lucide:sliders-horizontal", label: "Sliders" },
      { icon: "lucide:gauge", label: "Gauge" },
      { icon: "lucide:activity", label: "Activity" },
      { icon: "lucide:diamond", label: "Diamond" },
      { icon: "lucide:hash", label: "Hashtag" },
    ],
  },
  {
    id: "mdi",
    name: "Material Design",
    prefix: "mdi",
    icons: [
      { icon: "mdi:microphone", label: "Microphone" },
      { icon: "mdi:microphone-variant", label: "Mic Variant" },
      { icon: "mdi:music", label: "Music" },
      { icon: "mdi:music-note", label: "Note" },
      { icon: "mdi:music-note-eighth", label: "Eighth Note" },
      { icon: "mdi:music-note-sixteenth", label: "Sixteenth Note" },
      { icon: "mdi:music-clef-treble", label: "Treble Clef" },
      { icon: "mdi:guitar-acoustic", label: "Guitar" },
      { icon: "mdi:piano", label: "Piano" },
      { icon: "mdi:drum", label: "Drum" },
      { icon: "mdi:headphones", label: "Headphones" },
      { icon: "mdi:volume-high", label: "Volume High" },
      { icon: "mdi:volume-low", label: "Volume Low" },
      { icon: "mdi:volume-off", label: "Mute" },
      { icon: "mdi:waveform", label: "Waveform" },
      { icon: "mdi:sine-wave", label: "Sine Wave" },
      { icon: "mdi:bell", label: "Bell" },
      { icon: "mdi:lightning-bolt", label: "Bolt" },
      { icon: "mdi:fire", label: "Fire" },
      { icon: "mdi:heart", label: "Heart" },
      { icon: "mdi:star", label: "Star" },
      { icon: "mdi:weather-sunny", label: "Sun" },
      { icon: "mdi:weather-night", label: "Moon" },
      { icon: "mdi:cloud", label: "Cloud" },
      { icon: "mdi:weather-windy", label: "Wind" },
      { icon: "mdi:water", label: "Water" },
      { icon: "mdi:snowflake", label: "Snowflake" },
      { icon: "mdi:feather", label: "Feather" },
      { icon: "mdi:hand-wave", label: "Hand" },
      { icon: "mdi:emoticon-happy", label: "Smile" },
      { icon: "mdi:emoticon-sad", label: "Sad" },
      { icon: "mdi:alert-circle", label: "Exclamation" },
      { icon: "mdi:alert", label: "Warning" },
      { icon: "mdi:information", label: "Info" },
      { icon: "mdi:arrow-up", label: "Arrow Up" },
      { icon: "mdi:arrow-down", label: "Arrow Down" },
      { icon: "mdi:arrow-up-down", label: "Arrows Up Down" },
      { icon: "mdi:rotate-right", label: "Rotate" },
      { icon: "mdi:repeat", label: "Repeat" },
      { icon: "mdi:pause", label: "Pause" },
      { icon: "mdi:play", label: "Play" },
      { icon: "mdi:stop", label: "Stop" },
      { icon: "mdi:fast-forward", label: "Forward" },
      { icon: "mdi:rewind", label: "Backward" },
      { icon: "mdi:lungs", label: "Lungs" },
      { icon: "mdi:comment", label: "Comment" },
      { icon: "mdi:format-quote-open", label: "Quote" },
      { icon: "mdi:auto-fix", label: "Magic" },
      { icon: "mdi:signal", label: "Signal" },
      { icon: "mdi:tune-vertical", label: "Sliders" },
      { icon: "mdi:speedometer", label: "Gauge" },
      { icon: "mdi:diamond-stone", label: "Diamond" },
      { icon: "mdi:pound", label: "Hashtag" },
    ],
  },
  {
    id: "ph",
    name: "Phosphor",
    prefix: "ph",
    icons: [
      { icon: "ph:microphone-bold", label: "Microphone" },
      { icon: "ph:microphone-stage-bold", label: "Stage Mic" },
      { icon: "ph:music-notes-bold", label: "Music Notes" },
      { icon: "ph:music-note-bold", label: "Music Note" },
      { icon: "ph:guitar-bold", label: "Guitar" },
      { icon: "ph:headphones-bold", label: "Headphones" },
      { icon: "ph:speaker-high-bold", label: "Volume High" },
      { icon: "ph:speaker-low-bold", label: "Volume Low" },
      { icon: "ph:speaker-x-bold", label: "Mute" },
      { icon: "ph:waveform-bold", label: "Waveform" },
      { icon: "ph:bell-bold", label: "Bell" },
      { icon: "ph:lightning-bold", label: "Bolt" },
      { icon: "ph:fire-bold", label: "Fire" },
      { icon: "ph:heart-bold", label: "Heart" },
      { icon: "ph:star-bold", label: "Star" },
      { icon: "ph:sun-bold", label: "Sun" },
      { icon: "ph:moon-bold", label: "Moon" },
      { icon: "ph:cloud-bold", label: "Cloud" },
      { icon: "ph:wind-bold", label: "Wind" },
      { icon: "ph:drop-bold", label: "Water" },
      { icon: "ph:snowflake-bold", label: "Snowflake" },
      { icon: "ph:feather-bold", label: "Feather" },
      { icon: "ph:hand-waving-bold", label: "Hand" },
      { icon: "ph:smiley-bold", label: "Smile" },
      { icon: "ph:smiley-sad-bold", label: "Sad" },
      { icon: "ph:warning-circle-bold", label: "Exclamation" },
      { icon: "ph:warning-bold", label: "Warning" },
      { icon: "ph:info-bold", label: "Info" },
      { icon: "ph:arrow-up-bold", label: "Arrow Up" },
      { icon: "ph:arrow-down-bold", label: "Arrow Down" },
      { icon: "ph:arrows-down-up-bold", label: "Arrows Up Down" },
      { icon: "ph:arrow-clockwise-bold", label: "Rotate" },
      { icon: "ph:repeat-bold", label: "Repeat" },
      { icon: "ph:pause-bold", label: "Pause" },
      { icon: "ph:play-bold", label: "Play" },
      { icon: "ph:stop-bold", label: "Stop" },
      { icon: "ph:fast-forward-bold", label: "Forward" },
      { icon: "ph:rewind-bold", label: "Backward" },
      { icon: "ph:chat-circle-bold", label: "Comment" },
      { icon: "ph:quotes-bold", label: "Quote" },
      { icon: "ph:magic-wand-bold", label: "Magic" },
      { icon: "ph:sparkle-bold", label: "Sparkle" },
      { icon: "ph:wave-sine-bold", label: "Sine Wave" },
      { icon: "ph:cell-signal-full-bold", label: "Signal" },
      { icon: "ph:sliders-horizontal-bold", label: "Sliders" },
      { icon: "ph:gauge-bold", label: "Gauge" },
      { icon: "ph:diamond-bold", label: "Diamond" },
      { icon: "ph:hash-bold", label: "Hashtag" },
    ],
  },
  {
    id: "tabler",
    name: "Tabler",
    prefix: "tabler",
    icons: [
      { icon: "tabler:microphone", label: "Microphone" },
      { icon: "tabler:microphone-2", label: "Mic 2" },
      { icon: "tabler:music", label: "Music" },
      { icon: "tabler:music-bolt", label: "Music Bolt" },
      { icon: "tabler:guitar-pick", label: "Guitar Pick" },
      { icon: "tabler:headphones", label: "Headphones" },
      { icon: "tabler:volume", label: "Volume High" },
      { icon: "tabler:volume-2", label: "Volume Low" },
      { icon: "tabler:volume-off", label: "Mute" },
      { icon: "tabler:wave-sine", label: "Sine Wave" },
      { icon: "tabler:wave-saw-tool", label: "Saw Wave" },
      { icon: "tabler:bell", label: "Bell" },
      { icon: "tabler:bolt", label: "Bolt" },
      { icon: "tabler:flame", label: "Fire" },
      { icon: "tabler:heart", label: "Heart" },
      { icon: "tabler:star", label: "Star" },
      { icon: "tabler:sun", label: "Sun" },
      { icon: "tabler:moon", label: "Moon" },
      { icon: "tabler:cloud", label: "Cloud" },
      { icon: "tabler:wind", label: "Wind" },
      { icon: "tabler:droplet", label: "Water" },
      { icon: "tabler:snowflake", label: "Snowflake" },
      { icon: "tabler:feather", label: "Feather" },
      { icon: "tabler:hand-stop", label: "Hand" },
      { icon: "tabler:mood-smile", label: "Smile" },
      { icon: "tabler:mood-sad", label: "Sad" },
      { icon: "tabler:alert-circle", label: "Exclamation" },
      { icon: "tabler:alert-triangle", label: "Warning" },
      { icon: "tabler:info-circle", label: "Info" },
      { icon: "tabler:arrow-up", label: "Arrow Up" },
      { icon: "tabler:arrow-down", label: "Arrow Down" },
      { icon: "tabler:arrows-up-down", label: "Arrows Up Down" },
      { icon: "tabler:rotate-clockwise", label: "Rotate" },
      { icon: "tabler:repeat", label: "Repeat" },
      { icon: "tabler:player-pause", label: "Pause" },
      { icon: "tabler:player-play", label: "Play" },
      { icon: "tabler:player-stop", label: "Stop" },
      { icon: "tabler:player-track-next", label: "Forward" },
      { icon: "tabler:player-track-prev", label: "Backward" },
      { icon: "tabler:message", label: "Comment" },
      { icon: "tabler:quote", label: "Quote" },
      { icon: "tabler:wand", label: "Magic" },
      { icon: "tabler:sparkles", label: "Sparkles" },
      { icon: "tabler:signal-5g", label: "Signal" },
      { icon: "tabler:adjustments-horizontal", label: "Sliders" },
      { icon: "tabler:gauge", label: "Gauge" },
      { icon: "tabler:diamond", label: "Diamond" },
      { icon: "tabler:hash", label: "Hashtag" },
    ],
  },
];

/** Alle Icons aus allen Bibliotheken als flache Liste */
export const ALL_ICONS: IconChoice[] = ICON_LIBRARIES.flatMap((lib) => lib.icons);
