/**
 * Property 6: QuizGenerator schließt nicht-lernbare Inhalte aus
 *
 * For any SongDetail, all questions generated by generateMCQuestions,
 * generateReihenfolgeQuestions, and generateDiktatQuestions SHALL not reference
 * any stropheId belonging to an instrumental strophe, and no zeileId belonging
 * to a kommentar zeile.
 *
 * **Validates: Requirements 3.1, 4.1**
 */
// Feature: instrumental-annotations, Property 6: QuizGenerator schließt nicht-lernbare Inhalte aus

import { describe, it, expect } from "vitest";
import fc from "fast-check";
import {
  generateMCQuestions,
  generateReihenfolgeQuestions,
  generateDiktatQuestions,
} from "@/lib/quiz/quiz-generator";
import { arbSongDetail } from "./generators";

describe("Property 6: QuizGenerator schließt nicht-lernbare Inhalte aus", () => {
  it("generateMCQuestions does not reference instrumental strophes or kommentar zeilen", () => {
    fc.assert(
      fc.property(arbSongDetail, fc.nat(), (song, seed) => {
        const instrumentalIds = new Set(
          song.strophen.filter((s) => s.istInstrumental).map((s) => s.id),
        );
        const kommentarIds = new Set(
          song.strophen.flatMap((s) =>
            s.zeilen.filter((z) => z.istKommentar).map((z) => z.id),
          ),
        );

        const questions = generateMCQuestions(song, undefined, seed);
        for (const q of questions) {
          expect(instrumentalIds.has(q.stropheId)).toBe(false);
          expect(kommentarIds.has(q.zeileId)).toBe(false);
        }
      }),
      { numRuns: 100 },
    );
  });

  it("generateReihenfolgeQuestions does not reference instrumental strophes or kommentar zeilen", () => {
    fc.assert(
      fc.property(arbSongDetail, fc.nat(), (song, seed) => {
        const instrumentalIds = new Set(
          song.strophen.filter((s) => s.istInstrumental).map((s) => s.id),
        );
        const kommentarIds = new Set(
          song.strophen.flatMap((s) =>
            s.zeilen.filter((z) => z.istKommentar).map((z) => z.id),
          ),
        );

        const questions = generateReihenfolgeQuestions(song, undefined, seed);
        for (const q of questions) {
          expect(instrumentalIds.has(q.stropheId)).toBe(false);
          for (const z of q.shuffledZeilen) {
            expect(kommentarIds.has(z.zeileId)).toBe(false);
          }
          for (const zeileId of q.correctOrder) {
            expect(kommentarIds.has(zeileId)).toBe(false);
          }
        }
      }),
      { numRuns: 100 },
    );
  });

  it("generateDiktatQuestions does not reference instrumental strophes or kommentar zeilen", () => {
    fc.assert(
      fc.property(arbSongDetail, fc.nat(), (song, seed) => {
        const instrumentalIds = new Set(
          song.strophen.filter((s) => s.istInstrumental).map((s) => s.id),
        );
        const kommentarIds = new Set(
          song.strophen.flatMap((s) =>
            s.zeilen.filter((z) => z.istKommentar).map((z) => z.id),
          ),
        );

        const questions = generateDiktatQuestions(song, undefined, seed);
        for (const q of questions) {
          expect(instrumentalIds.has(q.stropheId)).toBe(false);
          expect(kommentarIds.has(q.zeileId)).toBe(false);
        }
      }),
      { numRuns: 100 },
    );
  });
});
